name: build
env:
    DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Generate '.xcodeproj'
      run: swift package generate-xcodeproj
    - name: Build
      run: |
        xcodebuild build clean\
         -scheme "RealityKitt-Package"\
         -sdk iphonesimulator\
         -destination "platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.5"
