name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint
        run: swiftlint
