name: test
env:
    DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate '.xcodeproj'
      run: swift package generate-xcodeproj
    - name: Test
      run: |
        xcodebuild clean test\
         -scheme "RealityKitt-Package"\
         -sdk iphonesimulator\
         -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=14.0"
